[package]
name = "p2termd"
version = "0.1.0"
edition = "2024"


[dependencies]
p2term-lib = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
iroh = { workspace = true }
portable-pty = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
termion = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true