[package]
name = "p2term-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
hex = { workspace = true }
iroh-base = { workspace = true }
rand_core = { workspace = true }
rand_chacha = { workspace = true }

[lints]
workspace = true
